echo "We are learning Branching"
echo "I am learning Git"
echo "Hello, How are you?"
echo "I am from batch-32"
echo "I am Ajay" 
echo "I am learning Github"
echo "I am Akshay Raje"
echo "I am the BEST!"